"""``python -m src.connectorlab`` — show what goes in and out of a connector.

Two modes:

* no arguments runs the whole walkthrough and writes the submission artifact
  (``--scene NAME`` narrows it);
* ``fetch github.pull_requests --where repo=ema/core`` answers one ad-hoc
  question, so a reviewer can see the call *their own* predicates produce rather
  than only the ones this file chose.

Both go through the real adapters. Nothing here constructs a URL.
"""

import argparse
import asyncio
import json
import sys
from pathlib import Path

from src.connectorlab import render
from src.connectorlab.scenes import SCENES
from src.connectorlab.wiring import DEFAULT_SCOPE, DEFAULT_TENANT, Lab, open_lab
from src.connectors.base import FetchRequest
from src.models.errors import ApiError

DEFAULT_ARTIFACT = Path("docs/artifacts/connectors/connector-walkthrough.txt")

#: Operators a `--where` may use. The same five the capability models declare;
#: anything else is refused here rather than inside the adapter, where the
#: message would be about a predicate the caller never knowingly wrote.
OPERATORS = ("<=", ">=", "=", "<", ">")


def parse_where(clause: str) -> tuple[str, tuple[str, str]]:
    """``state=open`` or ``updated>=2026-09-01`` -> ``("state", ("=", "open"))``."""
    for operator in OPERATORS:
        column, found, value = clause.partition(operator)
        if found and column:
            return column.strip(), (operator, value.strip())
    raise SystemExit(f"--where {clause!r} has no operator; expected one of {OPERATORS}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m src.connectorlab",
        description="Show the request a connector sends and the response it parses.",
    )
    # A flag rather than a positional: argparse hands a bare `nargs="*"`
    # positional to the subparser, so `... capabilities` is read as an unknown
    # SUBCOMMAND and rejected with a thoroughly misleading message.
    parser.add_argument(
        "--scene",
        action="append",
        default=[],
        choices=list(SCENES),
        metavar="NAME",
        help=f"run only this scene; repeatable. One of: {', '.join(SCENES)}",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_ARTIFACT,
        help="where to write the walkthrough (use - for stdout only)",
    )

    sub = parser.add_subparsers(dest="command")
    ad_hoc = sub.add_parser("fetch", help="answer one ad-hoc question")
    ad_hoc.add_argument("source", help="e.g. github.pull_requests")
    ad_hoc.add_argument("--where", action="append", default=[], metavar="COL=VALUE")
    ad_hoc.add_argument("--select", default="", help="comma-separated columns")
    ad_hoc.add_argument("--limit", type=int, default=3)
    ad_hoc.add_argument("--page", default=None, help="a cursor from a previous call")
    ad_hoc.add_argument("--tenant", default=DEFAULT_TENANT)
    ad_hoc.add_argument("--staleness", type=int, default=0, help="max_staleness_ms")
    ad_hoc.add_argument("--json", action="store_true", help="machine-readable output")
    return parser


async def run_walkthrough(lab: Lab, wanted: list[str]) -> list[str]:
    lines = [
        render.rule(),
        "  CONNECTOR WALKTHROUGH",
        "  generated by `python -m src.connectorlab` against the running stack",
        "",
        "  Every request and response below was produced by the real fetch path and",
        "  read back off the adapter. This tool prints; it never simulates.",
    ]
    for name in wanted or SCENES:
        lines += ["", *await SCENES[name](lab)]
    lines += ["", render.rule()]
    return lines


async def run_fetch(lab: Lab, args: argparse.Namespace) -> int:
    adapter = lab.adapter(args.source)
    predicates = dict(parse_where(clause) for clause in args.where)
    fetch_request = FetchRequest(
        tenant_id=args.tenant,
        entitlement_scope=DEFAULT_SCOPE,
        predicates=predicates,
        projection=[c.strip() for c in args.select.split(",") if c.strip()],
        limit=args.limit,
        page=args.page,
        max_staleness_ms=args.staleness,
    )
    try:
        result = await adapter.fetch(fetch_request)
    except ApiError as refused:
        # The capability model's own message, and a non-zero exit — a
        # refusal that printed like a result would be the worst possible output
        # for a tool whose job is showing what the contract allows.
        print(f"{refused.code.value}: {refused.message}", file=sys.stderr)
        return 1

    if args.json:
        print(
            json.dumps(
                {
                    "request": {
                        "method": adapter.last_request.method,
                        "url": adapter.last_request.redacted().url,
                        "headers": dict(adapter.last_request.redacted().headers),
                    },
                    "response": {
                        "status": adapter.last_response.status,
                        "headers": dict(adapter.last_response.headers),
                        "body": adapter.last_response.body,
                    },
                    "rows": result.rows,
                    "served": result.served,
                    "has_more": result.has_more,
                    "next_cursor": result.next_cursor,
                },
                indent=2,
                default=str,
            )
        )
        return 0

    for line in [
        *render.heading(f"{args.source}", f"tenant={args.tenant} {predicates or '(no filters)'}"),
        *render.request_block(adapter.last_request),
        "",
        *render.response_block(adapter.last_response),
        "",
        "  parsed rows:",
        *render.rows_block(result.rows, shown=args.limit),
        "",
        f"  served={result.served}  rows={len(result.rows)}  has_more={result.has_more}",
        f"  next --page {result.next_cursor}" if result.next_cursor else "  (last page)",
    ]:
        print(line)
    return 0


async def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    async with open_lab() as lab:
        if args.command == "fetch":
            return await run_fetch(lab, args)

        lines = await run_walkthrough(lab, args.scene)
        text = "\n".join(lines)
        print(text)
        if str(args.out) != "-":
            args.out.parent.mkdir(parents=True, exist_ok=True)
            args.out.write_text(f"{text}\n")
            print(f"\nwrote {args.out}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
