#!/usr/bin/env bash
#
# The scripted walkthrough. Four calls, four of the five hard parts, no UI and no
# observability stack — this is the artifact insurance named in the phase file:
# both other submission artifacts (the console screenshot, the trace waterfall)
# live in later phases, so a slip there would otherwise leave the submission with
# no demo at all.
#
#   1. alice  -> the entitled answer
#   2. bob    -> RLS visibly shrinks it (3 -> 1), same SQL
#   3. staleness knob, 0 then 60000 -> served flips live -> cache
#   4. forced Jira timeout -> partial, join_status incomplete, no cursor
#
# Requires: the stack up (`make up`), seeded (`make seed`), and TEST_MODE on for
# step 4 (`make demo` does that for you). bash + curl + python3 only — a reviewer
# runs this on a fresh clone, so it adds no dependency.

set -euo pipefail

BASE="${BASE_URL:-http://localhost:8000}"
OUT="${DEMO_OUTPUT:-docs/artifacts/demo/demo-output.txt}"
mkdir -p "$(dirname "$OUT")"
PY="${PYTHON:-.venv/bin/python}"

CANONICAL="SELECT pr.title, pr.author, issue.key, issue.status
FROM   github.pull_requests pr
JOIN   jira.issues issue ON pr.issue_key = issue.key
WHERE  pr.repo = 'ema/core' AND pr.state = 'open' AND issue.status = 'In Progress'
ORDER BY issue.updated DESC
LIMIT 50"

CLS_DEMO="SELECT pr.title, pr.author, issue.key, issue.status, issue.reporter_email
FROM   github.pull_requests pr
JOIN   jira.issues issue ON pr.issue_key = issue.key
WHERE  pr.repo = 'ema/core' AND pr.state = 'open' AND issue.status = 'In Progress'
ORDER BY issue.updated DESC
LIMIT 50"

mkdir -p "$(dirname "$OUT")"

token() {
  curl -fsS -XPOST "$BASE/v1/auth/mock-token" \
    -H 'content-type: application/json' \
    -d "{\"user\":\"$1\",\"role\":\"support\",\"tenant\":\"tenant_acme\"}" \
  | "$PY" -c 'import json,sys; print(json.load(sys.stdin)["token"])'
}

# Envelopes are printed through json.tool so the output file is readable as an
# artifact rather than as one long line.
query() {
  local user="$1" sql="$2" staleness="$3"
  curl -fsS -XPOST "$BASE/v1/query" \
    -H "authorization: Bearer $(token "$user")" \
    -H 'content-type: application/json' \
    -d "$("$PY" -c 'import json,sys; print(json.dumps({"sql": sys.argv[1], "max_staleness_ms": int(sys.argv[2])}))' "$sql" "$staleness")" \
  | "$PY" -m json.tool
}

banner() {
  echo
  echo "================================================================================"
  echo "  $1"
  echo "--------------------------------------------------------------------------------"
  echo "  $2"
  echo "================================================================================"
  echo
}

run_demo() {
  echo "Universal SQL — prototype demo"
  echo "generated by scripts/demo.sh against $BASE"
  echo

  # Start from a known state, or step 3's "live then cache" is whatever the last
  # run happened to leave behind.
  curl -fsS -XPOST "$BASE/v1/test/reset" >/dev/null

  banner "1. HARD PART 1 — query-time RLS. alice runs the canonical query." \
          "Expect 3 rows. The Jira adapter received assignee='alice', so the rows
  she is not entitled to were never fetched — not fetched and dropped."
  query alice "$CANONICAL" 0

  banner "2. HARD PART 1 — the SAME SQL as bob." \
          "Expect exactly 1 row. The query text is byte-identical; only the
  compiled plan differs. A count that shrinks but stays non-zero is the
  legible proof — zero would be indistinguishable from a broken query."
  query bob "$CANONICAL" 0

  banner "3. HARD PART 1 (CLS) + HARD PART 4 — masking, then the staleness knob." \
          "reporter_email comes back as an MD5 digest with masked=true; the raw
  address never appears. Then the same query with max_staleness_ms=60000:
  sources[].served flips live -> cache, stats.connector_ms empties, and
  rate_limit_status is NOT decremented — a cache hit spends no token."
  echo "--- max_staleness_ms=0 (forces a live fetch) ---"
  query alice "$CLS_DEMO" 0
  echo
  echo "--- max_staleness_ms=60000 (accepts the cached answer) ---"
  query alice "$CLS_DEMO" 60000

  banner "4. HARD PART 5 — honest degradation. Jira is forced to time out." \
          "Expect partial=true, join_status=incomplete, a SOURCE_TIMEOUT warning
  naming jira, and next_cursor=null. The GitHub rows are NOT passed off as
  the joined answer — an offset into an incomplete result is not stable."
  curl -fsS -XPOST "$BASE/v1/test/fail-next" \
    -H 'content-type: application/json' -d '{"connector":"jira","mode":"timeout"}' >/dev/null
  # max_staleness_ms=0 so the forced failure is actually reached rather than
  # short-circuited by the entry step 3 just cached.
  query alice "$CANONICAL" 0

  banner "Not shown here" \
          "HARD PART 2 (per-tenant rate limiting) — drain the bucket by re-running
  step 1 with max_staleness_ms=0 more than 7 times; tenant_acme's GitHub
  budget is 5+2 burst, so request 8 returns 429 RATE_LIMIT_EXHAUSTED with a
  Retry-After and a suggested_action naming the async path.
  HARD PART 3 (credential isolation) — pytest tests/unit/test_secrets.py."
}

run_demo | tee "$OUT"
echo
echo "wrote $OUT"
